spring:
  # 数据库配置
  data:
    mongodb:
      host: localhost
      port: 27017
      database: slg
  # 国际化配置
  messages:
    basename: static/i18n/messages
    encoding: UTF-8

slg:
  # Local Server
  ip: 127.0.0.1
  port: 8123

  # PVP Server
  pvp:
    ip: 127.0.0.1
    port: 8400
