spring:
  # 国际化配置
  messages:
    basename: static/i18n/messages
    encoding: UTF-8
## mysql
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/cheshuo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
  # 数据库配置
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cheshuo

cheshuo:
  ip: localhost
  server:
    tcp:
      enable: true
      port: 8400
    websocket:
      enable: true
      port: 8500
